//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusaMochiAuto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class KusaMochiAutoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KusaMochiAutoSettings defaultInstance = ((KusaMochiAutoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KusaMochiAutoSettings())));
        
        public static KusaMochiAutoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public short StopScriptKey {
            get {
                return ((short)(this["StopScriptKey"]));
            }
            set {
                this["StopScriptKey"] = value;
            }
        }
    }
}
